########################################
# General Configuration Settings
########################################

# Specific which configuration file to use for each data product (Daysim/Activitysim/Urbansim)
daysim_configuration = 'daysim\config\2023\configuration.toml'
activitysim_coniguration = 'activitysim\config\2023\configuration.toml'
urbansim_configuration = 'urbansim\config\2023\configuration.toml'