[project]
name = "survey-conversion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "activitysim==1.5.1",
    "h5py>=3.16.0",
    "psrcelmerpy",
    "pyodbc>=5.3.0",
    "toml>=0.10.2",
]

[tool.uv.sources]
psrcelmerpy = { git = "https://github.com/psrc/psrcelmerpy.git" }
