########################################
# General Configuration Settings
########################################

survey_year = "(2017, 2019)"

elmer_trip_table = "HHSurvey.v_trip_multiyear_modeling"
elmer_person_table = "HHSurvey.v_person_multiyear_modeling"
elmer_hh_table = "HHSurvey.v_household_multiyear_modeling"
elmer_person_day_table = "HHSurvey.v_day_multiyear_modeling"

input_dir = 'daysim/inputs/2017_2019'

# Project Output Directory
output_dir = 'R:/e2projects_two/2023_base_year/2017_2019_survey/test'

# Specify which components to run
run_locate_parcels = true
run_convert_format = true
run_clean = true
run_data_validation = true
run_attach_skims = true

debug = false
debug_person_id = []
# debug_person_id = ['19101794011']   # List of person IDs to iterate over in tour creation, empty list to process all

hh_weight_col = 'hh_weight_2023'
walk_to_transit_mode = 6
drive_to_transit_mode = 7
drive_to_transit_access_list = [
    "Drove and parked my own household's vehicle (or motorcycle)",
    "Drove and parked another vehicle (or motorcycle)",
    "Got dropped off in my own household's vehicle (or motorcycle)",
    "Got dropped off in another vehicle (or motorcycle)"
]

################################################
# Parcel Location (locate_parcels.py) Config
################################################
# Load Survey Data from Elmer or use CSV
use_elmer = true

# If not using Elmer, specify CSV directory of raw survey files 
# Expected files: trip.csv, hh.csv, person.csv
survey_input_dir = 'R:/e2projects_two/2023_base_year/2017_2019_survey/elmer'

# Set parcel file location
parcel_file_dir = 'R:/e2projects_two/SoundCast/Inputs/dev/landuse/2018/rtp_2018/parcels_urbansim.txt'
parcel_maz_file_dir = 'R:/e2projects_two/activitysim/conversion/geographic_crosswalks/parcel_taz_block_lookup.csv'

opurp_field = "origin_purpose_cat"
dpurp_field = "dest_purpose_cat"

# Spatial projection definitions
LAT_LNG_CRS = 'epsg:4326'    # Survey data expected in lat/lng format
WA_STATE_PLANE_CRS = 'epsg:2285'    # Projection of parcel and TAZ data; survey data is converted to this

# list of columns in "workplace" field that represent main work location as home
usual_workplace_home = ['At home (telecommute or self-employed with home office)']

# distance in feet for max allowable distance between collected XY data and acceptable land use
school_max_dist = 5280     # mile for distance near parcel with students

################################################
# Attach Skims (attach_skims.py) Config
################################################
# Specify soundcast root directory to obtain skim values
# NOTE: network location are very slow now, recommend using local runs
run_root = 'L:/RTP_2022/final_runs/sc_rtp_2018_final/soundcast'

# Assumed travel speeds of walk and bike modes (generated from distance skims)
bike_speed = 10 # miles per hour
walk_speed = 3 # miles per hour

hhid = 'hhno'
pno = 'pno'
home_purp = 0
work_purp = 1
change_mode_purp = 10
origin = 'otaz'
dest = 'dtaz'

# Heirarchy order for tour mode, per DaySim docs: 
# https://www.psrc.org/sites/default/files/2015psrc-modechoiceautomodels.pdf
# Drive to Transit > Walk to Transit > School Bus > HOV3+ > HOV2 > SOV > Bike > Walk > Other
mode_heirarchy = [7,6,8,9,5,4,3,2,1,10]

transit_mode_list = ['Ferry or water taxi',
                    'Commuter rail (Sounder, Amtrak)',
                    'Urban Rail (e.g., Link light rail, monorail)',
                    'Bus (public transit)',
                    'Other rail (e.g., streetcar)']

person_columns = [
        "hhno",
        "pno",
        "pptyp",
        "pagey",
        "pgend",
        "pwtyp",
        "pwpcl",
        "pwtaz",
        "pwautime",
        "pwaudist",
        "pstyp",
        "pspcl",
        "pstaz",
        "psautime",
        "psaudist",
        "puwmode",
        "puwarrp",
        "puwdepp",
        "ptpass",
        "ppaidprk",
        "pdiary",
        "pproxy",
        "psexpfac",
        "person_id",
        "person_id_original"
    ]

hh_columns = [
        "hhno",
        "hhsize",
        "hhvehs",
        "hhwkrs",
        "hhftw",
        "hhptw",
        "hhret",
        "hhoad",
        "hhuni",
        "hhhsc",
        "hh515",
        "hhcu5",
        "hhincome",
        "hownrent",
        "hrestype",
        "hhtaz",
        "hhparcel",
        "hhexpfac",
        "samptype",
    ]

trip_columns = [
        "hhno",
        "pno",
        "day",
        "tour",
        "half",
        "tseg",
        "tsvid",
        "opurp",
        "dpurp",
        "mode",
        "deptm",
        "otaz",
        "opcl",
        "dtaz",
        "dpcl",
        "oadtyp",
        "dadtyp",
        "arrtm",
        "trexpfac",
        "travcost",
        "travtime",
        "travdist",
        "pathtype",
        "mode_acc",
        "dorp",
        "endacttm",
        "trip_id",
        "person_id",
        "person_id_original"
    ]

tour_columns = [
        "hhno",
        "pno",
        "day",
        "tour",
        "jtindex",
        "parent",
        "subtrs",
        "pdpurp",
        "tlvorig",
        "tardest",
        "tlvdest",
        "tarorig",
        "toadtyp",
        "tdadtyp",
        "topcl",
        "totaz",
        "tdpcl",
        "tdtaz",
        "tmodetp",
        "tpathtp",
        "tautotime",
        "tautocost",
        "tautodist",
        "tripsh1",
        "tripsh2",
        "phtindx1",
        "phtindx2",
        "fhtindx1",
        "fhtindx2",
        "toexpfac",
        "person_id",
        "hhid_elmer",
        "person_id_original"
    ]

[pwtyp_map]
'hhftw' = 1
'hhptw' = 2

[pptyp_map]
'hhret' = 3
'hhoad' = 4
'hhuni' = 5
'hhhsc' = 6
'hh515' = 7
'hhcu5' = 8

# lookup for departure hour to skim times
[tod_dict]
0 = '20to5'
1 = '20to5'
2 = '20to5'
3 = '20to5'
4 = '20to5'
5 = '5to6'
6 = '6to7'
7 = '7to8'
8 = '8to9'
9 = '9to10'
10 = '10to14'
11 = '10to14'
12 = '10to14'
13 = '10to14'
14 = '14to15'
15 = '15to16'
16 = '16to17'
17 = '17to18'
18 = '18to20'
19 = '18to20'
20 = '20to5'
21 = '20to5'
22 = '20to5'
23 = '20to5'
24 = '20to5'

[purp_dict]
'wk' = 1
'sc' = 2
'es' = 3
'pb' = 4
'sh' = 5
'ml' = 6
'so' = 7
're' = 8
'me' = 9

# Create an ID to match skim naming method
[skim_mode_dict]
1 = 'walk'
2 = 'bike'
3 = 'sov'
4 = 'hov2'
5 = 'hov3'
6 = 'ivtwa'	# transit in-vehicle time
7 = 'sov'
8 = 'sov'   # assign school bus as sov
9 = 'sov'	# assign TNC/taxi as sov   # FIXME
10 = 'sov'	# assign other as sov