#inherit_settings: True

# activitysim run -c configs -d data -o output


# number of households to simulate
#households_sample_size:  100
# simulate all households
households_sample_size: 5000

chunk_size: 0

# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
# (if True, tables will be written if DEST_CHOICE_SAMPLE_TABLE_NAME is specified in individual model settings)
want_dest_choice_sample_tables: False

# - tracing

# trace household id; comment out or leave empty for no trace
# households with all tour types
trace_hh_id: 113430

# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
#trace_od:


# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHID: household_id
      PERSONS: hhsize
      workers: num_workers
      VEHICL: auto_ownership
      MAZ: home_zone_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
  - tablename: accessibility
    filename: accessibility.csv
    index_col: zone_id
    keep_columns:
      - auPkRetail
      - auPkTotal
      - auOpRetail
      - auOpTotal
      - trPkRetail
      - trPkTotal
      - trOpRetail
      - trOpTotal
      - nmRetail
      - nmTotal
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      COUNTY: county_id
    keep_columns:
      - TAZ
      - DISTRICT
      - SD
      - county_id
      - TOTHH
      - TOTPOP
      - TOTACRE
      - RESACRE
      - CIACRE
      - TOTEMP
      - AGE0519
      - RETEMPN
      - FPSEMPN
      - HEREMPN
      - OTHEMPN
      - AGREMPN
      - MWTEMPN
      - PRKCST
      - OPRKCST
      - area_type
      - HSENROLL
      - COLLFTE
      - COLLPTE
      - TOPOLOGY
      - TERMINAL
      - transit_score_scaled

#      - access_dist_transit

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: workplace_location

models:
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - write_data_dictionary
  - write_tables


output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6


# value_of_time = lognormal(np.log(median_value_of_time * mu), sigma).clip(min_vot, max_vot)

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
